name: Docker

on:
  push:
    tags:
       - '*'

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        tag: [x86_64_musl, armv7_musl, arm64_musl]
        include:
          - tag: x86_64_musl
            target: x86_64-unknown-linux-musl
          - tag: armv7_musl
            target: armv7-unknown-linux-musleabihf
          - tag: arm64_musl
            target: aarch64-linux-musl

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push image
        run: |
          IMAGE_ID=ghcr.io/chipp/build.musl.${{ matrix.tag }}

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build . \
             --push \
             --build-arg TARGET="${{ matrix.target }}" \
             --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
             --platform linux/amd64,linux/arm64 \
             --tag $IMAGE_ID:$VERSION \
             --tag $IMAGE_ID:latest \
             --cache-from=type=registry,ref=$IMAGE_ID:cache \
             --cache-to=type=registry,ref=$IMAGE_ID:cache,mode=max
