name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        variant: [x86_64_musl, armv7_musl, arm64_musl]
        host: [arm64, amd64]
        include:
          - variant: x86_64_musl
            target: x86_64-unknown-linux-musl
          - variant: armv7_musl
            target: armv7-unknown-linux-musleabihf
          - variant: arm64_musl
            target: aarch64-linux-musl
          - host: arm64
            os: ubuntu-24.04-arm
          - host: amd64
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test image
        run: |
          IMAGE_ID=ghcr.io/chipp/build.musl.${{ matrix.variant }}

          echo IMAGE_ID=$IMAGE_ID

          docker buildx build . \
             --output type=oci,tar=false,dest=local \
             --platform linux/${{ matrix.host }} \
             --cache-from=type=gha,scope=${{ matrix.variant }}-${{ matrix.host }} \
             --cache-to=type=gha,scope=${{ matrix.variant }}-${{ matrix.host }},mode=max \
             --build-arg TARGET="${{ matrix.target }}" \
             --tag $IMAGE_ID:test

          docker buildx build . \
            --file test.Dockerfile \
            --load \
            --platform linux/${{ matrix.host }} \
            --build-context base-builder-rs=oci-layout://local:test \
            --tag $IMAGE_ID:validate
