name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: [x86_64_musl, armv7_musl, arm64_musl]
        include:
          - tag: x86_64_musl
            target: x86_64-unknown-linux-musl
          - tag: armv7_musl
            target: armv7-unknown-linux-musleabihf
          - tag: arm64_musl
            target: aarch64-linux-musl

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and test image
        run: |
          IMAGE_ID=ghcr.io/chipp/build.musl.${{ matrix.tag }}

          echo IMAGE_ID=$IMAGE_ID

          docker buildx build . \
             --push \
             --build-arg TARGET="${{ matrix.target }}" \
             --tag $IMAGE_ID:test \
             --cache-from=type=registry,ref=$IMAGE_ID:cache-linux-amd64 \
             --cache-to=type=registry,ref=$IMAGE_ID:cache-linux-amd64,mode=max

          docker buildx build . \
            --file test.Dockerfile \
            --load \
            --build-arg VARIANT=${{ matrix.tag }} \
            --tag $IMAGE_ID:validate
